/*
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bitpesa.sdk.model;

import co.bitpesa.sdk.model.FieldSelectValidation;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FieldValidation
 */
public class FieldValidationTest {
    private final FieldValidation model = new FieldValidation();

    /**
     * Model tests for FieldValidation
     */
    @Test
    public void testFieldValidation() {
        // TODO: test FieldValidation
    }

    /**
     * Test the property 'presence'
     */
    @Test
    public void presenceTest() {
        // TODO: test presence
    }

    /**
     * Test the property 'inclusion'
     */
    @Test
    public void inclusionTest() {
        // TODO: test inclusion
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

}
