/*
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bitpesa.sdk.model;

import co.bitpesa.sdk.model.PayinMethod;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayinMethodRequest
 */
public class PayinMethodRequestTest {
    private final PayinMethodRequest model = new PayinMethodRequest();

    /**
     * Model tests for PayinMethodRequest
     */
    @Test
    public void testPayinMethodRequest() {
        // TODO: test PayinMethodRequest
    }

    /**
     * Test the property 'payinMethod'
     */
    @Test
    public void payinMethodTest() {
        // TODO: test payinMethod
    }

}
