/*
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bitpesa.sdk.model;

import co.bitpesa.sdk.model.PayinMethodDetailsMobile;
import co.bitpesa.sdk.model.PayinMethodDetailsNGNBank;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayinMethodDetails
 */
public class PayinMethodDetailsTest {
    private final PayinMethodDetails model = new PayinMethodDetails();

    /**
     * Model tests for PayinMethodDetails
     */
    @Test
    public void testPayinMethodDetails() {
        // TODO: test PayinMethodDetails
    }

}
