/*
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bitpesa.sdk.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodMobileProviderEnum
 */
public class PayoutMethodMobileProviderEnumTest {
    /**
     * Model tests for PayoutMethodMobileProviderEnum
     */
    @Test
    public void testPayoutMethodMobileProviderEnum() {
        // TODO: test PayoutMethodMobileProviderEnum
    }

}
