/*
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bitpesa.sdk.model;

import co.bitpesa.sdk.model.PayoutMethodBankAccountTypeEnum;
import co.bitpesa.sdk.model.PayoutMethodDetailsBalance;
import co.bitpesa.sdk.model.PayoutMethodDetailsGHSBank;
import co.bitpesa.sdk.model.PayoutMethodDetailsIBAN;
import co.bitpesa.sdk.model.PayoutMethodDetailsMADCash;
import co.bitpesa.sdk.model.PayoutMethodDetailsMobile;
import co.bitpesa.sdk.model.PayoutMethodDetailsNGNBank;
import co.bitpesa.sdk.model.PayoutMethodDetailsXOFMobile;
import co.bitpesa.sdk.model.PayoutMethodGenderEnum;
import co.bitpesa.sdk.model.PayoutMethodIdentityCardTypeEnum;
import co.bitpesa.sdk.model.PayoutMethodMobileProviderEnum;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodDetails
 */
public class PayoutMethodDetailsTest {
    private final PayoutMethodDetails model = new PayoutMethodDetails();

    /**
     * Model tests for PayoutMethodDetails
     */
    @Test
    public void testPayoutMethodDetails() {
        // TODO: test PayoutMethodDetails
    }

}
