/*
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.bitpesa.sdk.model;

import co.bitpesa.sdk.model.WebhookDefinition;
import co.bitpesa.sdk.model.WebhookLogMetadataRequest;
import co.bitpesa.sdk.model.WebhookLogMetadataResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WebhookLogMetadata
 */
public class WebhookLogMetadataTest {
    private final WebhookLogMetadata model = new WebhookLogMetadata();

    /**
     * Model tests for WebhookLogMetadata
     */
    @Test
    public void testWebhookLogMetadata() {
        // TODO: test WebhookLogMetadata
    }

    /**
     * Test the property 'params'
     */
    @Test
    public void paramsTest() {
        // TODO: test params
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'instanceId'
     */
    @Test
    public void instanceIdTest() {
        // TODO: test instanceId
    }

    /**
     * Test the property 'instanceType'
     */
    @Test
    public void instanceTypeTest() {
        // TODO: test instanceType
    }

    /**
     * Test the property 'attemptId'
     */
    @Test
    public void attemptIdTest() {
        // TODO: test attemptId
    }

    /**
     * Test the property 'tries'
     */
    @Test
    public void triesTest() {
        // TODO: test tries
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'apiKeyId'
     */
    @Test
    public void apiKeyIdTest() {
        // TODO: test apiKeyId
    }

}
